#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

echo "downloading servicemix"
dl http://apache.mirrors.pair.com/servicemix/servicemix-7/7.0.0/apache-servicemix-7.0.0.zip /usr/local/src
